version: '3'

services:
  elasticsearch:     
    container_name: elasticsearch 
    build:
      context: elasticsearch
      args:
         ELK_VERSION: 7.5.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/storage:/usr/share/elasticsearch/data:rw

    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      - ELASTIC_PASSWORD="sewerage23"
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=*        
    networks:
      - elk
             
  
  logstash:
    container_name: logstash
    build:
       context: logstash
       args:
         ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline     
    ports:
      - "5000:5000"  
    networks:
      - elk    
    depends_on:
      - elasticsearch
  kibana:
     container_name: kibana
     build:
       context: kibana/
       args:
         ELK_VERSION: $ELK_VERSION
     volumes:
       - ./kibana/config/:/usr/share/kibana/config
     ports:
       - "5601:5601"
     environment:
       - ELASTICSEARCH_PASSWORD="changeme"
     networks:
       - elk
     depends_on:
       - elasticsearch

networks:
 elk:
   driver: bridge

